spring:
  application:
    name: retry
  datasource:
    url: jdbc:postgresql://localhost:54316/postgres?currentSchema=public
    username: postgres
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always

app:
  retry:
    test:
      max-attempts: 5
      initial-delay-millis: 1000
      multiplier: 1
      max-delay-millis: 5000
      jitter-millis: 200

logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: DEBUG